watch_stylesheet: true
watch_config: true
debug: false
bars:
  status-bar:
    enabled: true
    screens: ['primary']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
        [
          "home",
          "quick_launch",
          "apps"
        ]
      center:
        [
          "clock"
        ]
      right:
        [
          "systray",
          "cpu",
          "memory",
          "open_meteo",
          "wallpaper",
          "update",
          "power_menu"
        ]
widgets:
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {icon: "Brave", launch: "cmd /c start brave"}
        - {icon: "Steam", launch: "C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Steam\\Steam.lnk"}
        - {icon: "Discord", launch: "C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Discord Inc\\Discord.lnk"}
        - {icon: "VSCode", launch: "code"}
  quick_launch:
    type: "yasb.quick_launch.QuickLaunchWidget"
    options:
      label: "<span>\uf002</span>"
      search_placeholder: "Search applications..."
      max_results: 7
      show_icons: true
      icon_size: 16
      compact_text: true
      providers:
        apps:
          enabled: true
          prefix: "*"
          priority: 0
          show_recent: true
          max_recent: 5
          show_description: true
      popup:
        width: 720
        height: 280
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        dark_mode: true
      callbacks:
        on_left: "toggle_quick_launch"
      keybindings:
        - keys: "alt+s"
          action: "toggle_quick_launch"
          screen: "primary"
  wallpaper:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\Administrator\\Pictures\\Best"
      change_automatically: false # Automatically change wallpaper
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 200
        image_per_page: 7
        show_buttons: true
        orientation: "portrait"
        image_spacing: 10
        lazy_load: false
        lazy_load_delay: 80
        lazy_load_fadein: 200
        image_corner_radius: 8
        enable_cache: true
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "~\\Downloads"}
        - { title: "Pictures", path: "~\\Pictures"}
        - { title: "C:", path: "C:\\"}
        - { title: "D:", path: "D:\\"}
        - { title: "E:", path: "E:\\"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "system"
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  open_meteo:
    type: "yasb.open_meteo.OpenMeteoWidget"
    options:
      label: "<span>\ue30d</span>{temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      tooltip: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue314"
      weather_card:
        blur: true
        alignment: "right"
        direction: "down"
        icon_size: 32
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 16
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "system"
        current_line_width: 1
        current_line_style: "dot"
        hourly_forecast_buttons:
          enabled: false
        weather_animation:
          enabled: true
          snow_overrides_rain: true
          temp_line_animation_style: both
          rain_effect_intensity: 1.0
          snow_effect_intensity: 1.0
          scale_with_chance: true
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▲"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_battery: false
      show_volume: false
      show_network: false
      use_hook: true
      show_in_popup: true
      icons_per_row: 5
      popup:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%H:%M}"
      timezones: [] #Looking up time zone info from registry
      calendar:
        alignment: "center"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 100
      button_row: 5
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        sleep: ["\udb82\udd04","Sleep"]
        cancel: ["\udb81\udf3a","Cancel"]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "{info[percent][total]:.0f}%"
      label_alt: "{info[percent][total]:.0f}%"
      progress_bar:
        enabled: true
        position: "left"
        size: 16
        thickness: 2
        color: "#ffffff"
        background_color: "#242739" 
      menu:
        enabled: true
        show_graph: true
        show_graph_grid: true
        graph_history_size: 60
      update_interval: 2000
      callbacks:
        on_left: toggle_menu
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "{virtual_mem_used}"
      label_alt: "{virtual_mem_used}"
      update_interval: 5000
      progress_bar:
        enabled: true
        size: 16
        thickness: 2
        color: "#ffffff"
        background_color: "#242739" 
      callbacks:
        on_left: "toggle_menu"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      menu:
        enabled: true
        show_graph: true
        show_graph_grid: true
        graph_history_size: 60
  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 180
        exclude: []
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
  grouped_widgets:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "grouped-widgets"
      widgets: [
        "memory",
        "cpu",
      ]
      container_padding:
        top: 0
        left: 2
        bottom: 0
        right: 4
